export const ideaBuilderStyles = {
  documentActions: "flex items-center gap-2",
  pickerButton: "flex h-11 w-11 cursor-pointer items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-700 shadow-lg hover:bg-slate-50 aria-pressed:border-indigo-500 aria-pressed:bg-indigo-50 aria-pressed:text-indigo-700 disabled:cursor-not-allowed disabled:opacity-40",
  elementSelection: "rounded-xl border border-indigo-200 bg-indigo-50 p-3 text-xs text-indigo-900",
  elementHeader: "flex items-center justify-between gap-2 font-semibold",
  elementPath: "mt-2 block max-h-24 overflow-y-auto break-all text-xs leading-5",
  messageElement: "mb-2 block break-all border-b border-current/20 pb-2 text-xs leading-5",
  stopButton: "flex h-[25px] w-[25px] shrink-0 cursor-pointer items-center justify-center rounded-full border-0 bg-slate-800 text-white hover:bg-slate-700 disabled:cursor-not-allowed disabled:opacity-50",
  settingsButton: "flex h-11 w-11 shrink-0 cursor-pointer items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-600 transition hover:bg-slate-50 focus-visible:outline-indigo-600",
  root: "relative min-h-screen bg-[#f4f5f7] text-slate-950",
  chatSidebar: "fixed right-4 top-4 z-30 flex min-w-0 flex-col overflow-hidden rounded-3xl border border-white/80 bg-white/95 shadow-[0_16px_48px_-12px_rgba(15,23,42,0.24),0_2px_8px_rgba(15,23,42,0.06)] backdrop-blur-xl",
  chatSidebarHeader: "flex h-14 shrink-0 items-center gap-2 px-2",
  chatSidebarTitle: "min-w-0 truncate text-sm font-semibold text-slate-700",
  chatSidebarBodyExpanded: "flex min-h-0 flex-1 flex-col gap-3 px-4 pb-5 opacity-100 transition-opacity duration-200 delay-100 motion-reduce:transition-none",
  chatSidebarBodyCollapsed: "pointer-events-none flex min-h-0 flex-1 flex-col gap-3 overflow-hidden px-4 pb-5 opacity-0 transition-opacity duration-100 motion-reduce:transition-none",
  chatSidebarResize: "absolute inset-y-0 left-0 z-30 w-2 cursor-col-resize touch-none select-none hover:bg-indigo-400/30 focus-visible:bg-indigo-400/30 focus-visible:outline-none",
  documentButton: "flex h-11 w-11 cursor-pointer items-center justify-center rounded-xl border border-slate-200 bg-white text-slate-700 shadow-lg hover:bg-slate-50 focus-visible:outline-indigo-600",
  documentHeader: "flex items-center justify-between text-sm font-semibold text-slate-700",
  sidebar: "fixed left-4 top-4 z-30 flex min-w-0 flex-col overflow-hidden rounded-3xl border border-white/80 bg-white/95 shadow-[0_16px_48px_-12px_rgba(15,23,42,0.24),0_2px_8px_rgba(15,23,42,0.06)] backdrop-blur-xl",
  sidebarToolbar: "flex h-14 shrink-0 items-center justify-end px-2",
  sidebarToggle: "flex h-9 w-9 cursor-pointer items-center justify-center rounded-lg border-0 bg-transparent text-xl text-slate-500 hover:bg-slate-100 focus-visible:outline-indigo-600",
  sidebarBody: "flex min-h-0 flex-1 flex-col px-5 pb-7",
  sidebarMotion: "transition-[width,height] duration-300 ease-[cubic-bezier(0.22,1,0.36,1)] motion-reduce:transition-none",
  sidebarBodyExpanded: "flex min-h-0 flex-1 flex-col px-5 pb-7 opacity-100 transition-opacity duration-200 delay-100 motion-reduce:transition-none",
  sidebarBodyCollapsed: "pointer-events-none flex min-h-0 flex-1 flex-col overflow-hidden px-5 pb-7 opacity-0 transition-opacity duration-100 motion-reduce:transition-none",
  sidebarContent: "min-h-0 flex-1 overflow-y-auto",
  folderEmpty: "flex min-h-0 flex-1 items-center justify-center",
  folderEmptyGroup: "flex flex-col items-center gap-3",
  folderEmptyIcon: "text-slate-400",
  folderEmptyMessage: "m-0 text-center text-sm text-slate-500",
  folderSelectButton: "cursor-pointer rounded-md border-0 bg-transparent px-2 py-1 text-sm font-medium text-indigo-600 hover:text-indigo-700 hover:underline focus-visible:outline-indigo-600",
  sidebarResize: "absolute inset-y-0 right-0 z-30 w-2 cursor-col-resize touch-none select-none hover:bg-indigo-400/30 focus-visible:bg-indigo-400/30 focus-visible:outline-none",
  sidebarResizeOverlay: "fixed inset-0 z-40 cursor-col-resize select-none",
  eyebrow: "mb-2 text-[11px] font-bold uppercase tracking-[0.18em] text-indigo-600",
  main: "relative top-4 h-[calc(100vh-32px)] min-w-0 overflow-hidden rounded-2xl bg-white",
  mainMotion: "transition-[margin-left,margin-right] duration-300 ease-[cubic-bezier(0.22,1,0.36,1)] motion-reduce:transition-none",
  workspaceHeader: "mb-5 flex items-center justify-between gap-3",
  workspaceName: "min-w-0 flex-1 truncate text-sm font-bold text-slate-900",
  changeFolderButton: "cursor-pointer border-0 bg-transparent p-0 text-xs font-bold text-indigo-600",
  folderList: "m-0 flex list-none flex-col gap-1 overflow-y-auto p-0",
  folderItemRoot: "relative",
  folderItem: "flex w-full cursor-pointer items-center gap-2 rounded-lg border-0 bg-transparent px-2 py-2 text-left text-sm text-slate-600 hover:bg-slate-100",
  folderItemSelected: "flex w-full cursor-pointer items-center gap-2 rounded-lg border-0 bg-indigo-50 px-2 py-2 text-left text-sm font-semibold text-indigo-700",
  folderIcon: "shrink-0 text-slate-400",
  renameInput: "w-full rounded-lg border border-indigo-300 bg-white px-2 py-2 text-sm text-slate-800 outline-none ring-4 ring-indigo-50",
  contextMenu: "fixed z-[9999] w-32 overflow-hidden rounded-xl border border-slate-200 bg-white p-1 shadow-2xl",
  contextMenuItem: "w-full cursor-pointer rounded-lg border-0 bg-transparent px-3 py-2 text-left text-xs font-medium text-slate-700 hover:bg-slate-100",
  contextMenuDelete: "w-full cursor-pointer rounded-lg border-0 bg-transparent px-3 py-2 text-left text-xs font-medium text-rose-600 hover:bg-rose-50",
  sidebarActions: "mt-4 flex items-center gap-2",
  sidebarGenerateButton: "flex h-11 min-w-0 flex-1 cursor-pointer items-center justify-center gap-1.5 rounded-xl border-0 bg-indigo-600 px-4 text-sm font-bold text-white transition hover:bg-indigo-700 disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-400",
  button: "w-full cursor-pointer rounded-xl border-0 bg-slate-900 px-4 py-3 text-sm font-bold text-white transition hover:bg-indigo-600 disabled:cursor-not-allowed disabled:opacity-40",
  status: "rounded-xl bg-emerald-50 px-3 py-2.5 text-sm font-medium text-emerald-700",
  error: "rounded-xl bg-rose-50 px-3 py-2.5 text-sm font-medium text-rose-700",
  preview: "block h-full w-full border-0 bg-white",
  empty: "flex h-full w-full items-center justify-center bg-slate-50 px-10 text-center text-sm leading-6 text-slate-400",
  composerRoot: "fixed bottom-6 right-6 z-50 flex flex-col items-end gap-3",
  composerPanel: "flex h-[420px] w-[360px] flex-col gap-3 rounded-3xl border border-slate-200 bg-white p-5 shadow-2xl shadow-slate-900/15",
  modeSelector: "grid grid-cols-2 rounded-xl bg-slate-100 p-1",
  modeButton: "cursor-pointer rounded-lg border-0 bg-transparent px-3 py-2 text-xs font-semibold text-slate-500 transition hover:text-slate-800",
  modeButtonSelected: "cursor-pointer rounded-lg border-0 bg-white px-3 py-2 text-xs font-bold text-slate-900 shadow-sm",
  chatMessages: "flex min-h-0 flex-1 flex-col gap-2 overflow-y-auto rounded-2xl bg-slate-50 p-3",
  progressPanel: "rounded-2xl bg-white px-3 py-2 text-xs text-slate-600 shadow-sm",
  progressTitle: "m-0 mb-2 font-medium text-slate-800",
  progressList: "m-0 flex list-none flex-col gap-2 p-0",
  progressItem: "flex items-center justify-between gap-3",
  progressWaiting: "m-0 mt-2 text-slate-400",
  chatEmpty: "m-auto text-center text-xs text-slate-400",
  userBubble: "m-0 max-w-[85%] self-end whitespace-pre-wrap rounded-2xl rounded-br-md bg-indigo-600 px-3 py-2 text-sm leading-5 text-white",
  agentBubble: "m-0 max-w-[85%] self-start whitespace-pre-wrap rounded-2xl rounded-bl-md bg-white px-3 py-2 text-sm leading-5 text-slate-700 shadow-sm",
  chatInputRow: "flex flex-col gap-1 rounded-2xl bg-slate-50 p-1 focus-within:ring-2 focus-within:ring-indigo-400",
  chatInput: "max-h-24 min-h-10 w-full resize-none border-0 bg-transparent px-2 py-2.5 text-sm outline-none",
  chatInputActions: "flex min-w-0 items-center justify-between gap-2 px-1 pb-1",
  chatModelSelect: "min-w-0 flex-1 cursor-pointer truncate rounded-md border-0 bg-transparent px-1 py-0.5 text-xs text-slate-500 outline-none disabled:cursor-not-allowed disabled:opacity-50",
  reasoningControl: "relative shrink-0",
  reasoningButton: "flex h-[25px] w-[25px] cursor-pointer items-center justify-center rounded-full border-0 bg-transparent text-slate-500 hover:bg-slate-200 aria-expanded:bg-indigo-100 aria-expanded:text-indigo-700 disabled:cursor-not-allowed disabled:opacity-50",
  reasoningPopover: "fixed z-50 w-56 rounded-xl border border-slate-200 bg-white p-4 text-slate-700 shadow-xl",
  reasoningHeader: "flex items-center justify-between text-xs",
  reasoningSlider: "mt-3 w-full cursor-pointer accent-indigo-600",
  reasoningScale: "flex justify-between text-[10px] text-slate-400",
  chatModelError: "m-0 text-xs text-rose-600",
  sendButton: "flex h-[25px] w-[25px] shrink-0 cursor-pointer items-center justify-center rounded-full border-0 bg-indigo-600 text-white disabled:cursor-not-allowed disabled:opacity-40",
  titleInput: "w-full rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm font-semibold text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-indigo-400 focus:ring-4 focus:ring-indigo-50",
  composerTextarea: "min-h-0 w-full flex-1 resize-none rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6 outline-none transition placeholder:text-slate-400 focus:border-indigo-400 focus:ring-4 focus:ring-indigo-50",
  composerHint: "mt-3 text-center text-xs text-amber-600",
  fab: "flex h-14 w-14 cursor-pointer items-center justify-center rounded-full border-0 bg-indigo-600 text-3xl font-light leading-none text-white shadow-xl shadow-indigo-600/30 transition hover:bg-indigo-700 hover:scale-105",
};
