export const settingsStyles = {
  modelHeader: "mb-3 mt-6 flex items-center justify-between gap-3",
  refresh: "cursor-pointer rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-xs font-semibold text-slate-600 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50",
  select: "w-full cursor-pointer rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 focus:border-indigo-500 focus:outline-indigo-500 disabled:cursor-not-allowed disabled:opacity-50",
  root: "h-full overflow-y-auto bg-slate-50 px-8 py-10",
  content: "mx-auto max-w-2xl",
  back: "mb-8 cursor-pointer rounded-lg border-0 bg-transparent px-0 py-2 text-sm font-semibold text-slate-500 hover:text-indigo-600 focus-visible:outline-indigo-600",
  title: "m-0 text-3xl font-bold tracking-tight text-slate-900",
  description: "mb-8 mt-3 text-sm leading-6 text-slate-500",
  group: "m-0 min-w-0 rounded-2xl border border-slate-200 bg-white p-6",
  legend: "px-2 text-sm font-semibold text-slate-900",
  option: "mb-3 flex cursor-pointer items-start gap-4 rounded-xl border border-slate-200 p-5 transition hover:border-indigo-300 has-[:checked]:border-indigo-500 has-[:checked]:bg-indigo-50/50 has-[:disabled]:cursor-not-allowed",
  radio: "mt-1 h-4 w-4 cursor-pointer accent-indigo-600 disabled:cursor-not-allowed",
  name: "block text-sm font-bold text-slate-900",
  detail: "mt-1 block text-sm leading-6 text-slate-500",
  note: "mb-0 mt-4 text-xs leading-6 text-slate-500",
  status: "mt-4 text-sm text-emerald-700",
  error: "mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700",
};
